-- XANH SKY FIRST - Production hardening v3
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS content_revisions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  content_id INTEGER NOT NULL,
  snapshot_json TEXT NOT NULL,
  created_by INTEGER,
  created_at TEXT NOT NULL,
  FOREIGN KEY(content_id) REFERENCES content_items(id) ON DELETE CASCADE,
  FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_content_revisions_item ON content_revisions(content_id, created_at DESC);

CREATE TABLE IF NOT EXISTS form_uploads (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  form_id INTEGER NOT NULL,
  upload_token_hash TEXT NOT NULL UNIQUE,
  r2_key TEXT NOT NULL UNIQUE,
  filename TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  size_bytes INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  claimed_submission_id INTEGER,
  FOREIGN KEY(form_id) REFERENCES forms(id) ON DELETE CASCADE,
  FOREIGN KEY(claimed_submission_id) REFERENCES form_submissions(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_form_uploads_form ON form_uploads(form_id, created_at DESC);

CREATE TABLE IF NOT EXISTS submission_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  submission_id INTEGER NOT NULL,
  event_type TEXT NOT NULL,
  old_status TEXT,
  new_status TEXT,
  note TEXT NOT NULL DEFAULT '',
  actor_user_id INTEGER,
  email_sent INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  FOREIGN KEY(submission_id) REFERENCES form_submissions(id) ON DELETE CASCADE,
  FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_submission_events_submission ON submission_events(submission_id, created_at DESC);
INSERT OR IGNORE INTO pages(slug,title,status,blocks_json,seo_json,published_at,created_at,updated_at) VALUES ('quyen-rieng-tu','Quyền riêng tư','published','[{"type": "heading", "text": "Quyền riêng tư"}, {"type": "paragraph", "text": "Xanh Sky First tôn trọng quyền riêng tư của người truy cập, người tham gia hoạt động, tình nguyện viên và những người gửi thông tin qua các biểu mẫu trên website. Chúng tôi chỉ thu thập những dữ liệu cần thiết cho mục đích đã được trình bày tại thời điểm thu thập, chẳng hạn như xác nhận đăng ký, liên hệ về một chương trình, xử lý đề xuất sáng kiến hoặc gửi newsletter khi người dùng chủ động lựa chọn. Dữ liệu không được tự động chuyển từ một biểu mẫu sang danh sách nhận bản tin và không được công khai chỉ vì người dùng đã gửi hồ sơ. Quyền truy cập dữ liệu nội bộ được giới hạn theo vai trò quản trị và hoạt động truy cập, chỉnh sửa quan trọng có thể được ghi nhận trong nhật ký hệ thống. Người dùng có thể liên hệ support@skyfirst.io.vn để yêu cầu kiểm tra, cập nhật hoặc đề nghị xử lý dữ liệu liên quan đến mình sau khi hoàn tất bước xác minh phù hợp."}, {"type": "heading", "text": "Liên hệ về nội dung này"}, {"type": "paragraph", "text": "Mọi phản hồi hoặc yêu cầu liên quan có thể gửi tới support@skyfirst.io.vn. Khi yêu cầu liên quan đến một hồ sơ cụ thể, Xanh có thể cần thông tin xác minh hợp lý trước khi cung cấp, chỉnh sửa hoặc xử lý dữ liệu nhằm bảo vệ quyền riêng tư của chính người gửi."}]','{"title": "Quyền riêng tư | Xanh Sky First", "description": "Xanh Sky First tôn trọng quyền riêng tư của người truy cập, người tham gia hoạt động, tình nguyện viên và những người gửi thông tin qua các biểu mẫu trên w"}',datetime('now'),datetime('now'),datetime('now'));
INSERT OR IGNORE INTO pages(slug,title,status,blocks_json,seo_json,published_at,created_at,updated_at) VALUES ('dieu-khoan','Điều khoản sử dụng','published','[{"type": "heading", "text": "Điều khoản sử dụng"}, {"type": "paragraph", "text": "Website Xanh Sky First cung cấp thông tin, tài nguyên, cơ hội tham gia và các biểu mẫu phục vụ hoạt động môi trường, cộng đồng và phát triển bền vững. Khi sử dụng website, người dùng đồng ý không thực hiện các hành vi gây gián đoạn hệ thống, dò quét trái phép, gửi nội dung có mã độc, giả mạo danh tính, spam hoặc khai thác dữ liệu của người khác ngoài mục đích được cho phép. Thông tin về lịch hoạt động, số lượng tiếp nhận, trạng thái dự án và cơ hội tham gia có thể được điều chỉnh khi điều kiện triển khai thực tế thay đổi; Xanh sẽ cố gắng cập nhật thông tin tại chính trang liên quan thay vì duy trì nội dung đã lỗi thời. Những liên kết dẫn đến hệ thống bên ngoài được cung cấp để hỗ trợ người dùng và có thể chịu điều khoản riêng của nền tảng đó. Việc sử dụng website không tạo ra quan hệ lao động, học thuật, cấp chứng nhận nhà nước hoặc quan hệ pháp lý khác nếu không có văn bản riêng quy định."}, {"type": "heading", "text": "Liên hệ về nội dung này"}, {"type": "paragraph", "text": "Mọi phản hồi hoặc yêu cầu liên quan có thể gửi tới support@skyfirst.io.vn. Khi yêu cầu liên quan đến một hồ sơ cụ thể, Xanh có thể cần thông tin xác minh hợp lý trước khi cung cấp, chỉnh sửa hoặc xử lý dữ liệu nhằm bảo vệ quyền riêng tư của chính người gửi."}]','{"title": "Điều khoản sử dụng | Xanh Sky First", "description": "Website Xanh Sky First cung cấp thông tin, tài nguyên, cơ hội tham gia và các biểu mẫu phục vụ hoạt động môi trường, cộng đồng và phát triển bền vững. Khi "}',datetime('now'),datetime('now'),datetime('now'));
INSERT OR IGNORE INTO pages(slug,title,status,blocks_json,seo_json,published_at,created_at,updated_at) VALUES ('chinh-sach-du-lieu','Chính sách dữ liệu & hình ảnh','published','[{"type": "heading", "text": "Chính sách dữ liệu & hình ảnh"}, {"type": "paragraph", "text": "Xanh Sky First xử lý dữ liệu phát sinh từ biểu mẫu đăng ký, hồ sơ tình nguyện viên, đề xuất sáng kiến, thông tin liên hệ, tài liệu tải lên và hình ảnh hoạt động theo mục đích vận hành đã được thông báo. Dữ liệu nhạy cảm hoặc dữ liệu không cần thiết không nên được yêu cầu chỉ để làm đầy hồ sơ. Tệp tải lên được lưu trong hạ tầng lưu trữ của hệ thống và chỉ nên được truy cập theo đúng vai trò được phân quyền. Đối với hình ảnh hoạt động, việc sử dụng cho truyền thông cần phù hợp với phạm vi đã thông báo và phải đặc biệt thận trọng khi hình ảnh có người chưa thành niên. Khi một chương trình có người chưa thành niên tham gia, biểu mẫu cần có cơ chế đồng ý, thông tin người giám hộ hoặc biện pháp bảo vệ phù hợp với bối cảnh thực tế. Thời gian lưu trữ được xác định theo nhu cầu vận hành, nghĩa vụ liên quan và khả năng giải quyết yêu cầu sau chương trình; dữ liệu không còn cần thiết nên được xem xét xóa hoặc giảm khả năng nhận diện. Các yêu cầu truy cập, sửa hoặc xóa dữ liệu có thể gửi tới support@skyfirst.io.vn."}, {"type": "heading", "text": "Liên hệ về nội dung này"}, {"type": "paragraph", "text": "Mọi phản hồi hoặc yêu cầu liên quan có thể gửi tới support@skyfirst.io.vn. Khi yêu cầu liên quan đến một hồ sơ cụ thể, Xanh có thể cần thông tin xác minh hợp lý trước khi cung cấp, chỉnh sửa hoặc xử lý dữ liệu nhằm bảo vệ quyền riêng tư của chính người gửi."}]','{"title": "Chính sách dữ liệu & hình ảnh | Xanh Sky First", "description": "Xanh Sky First xử lý dữ liệu phát sinh từ biểu mẫu đăng ký, hồ sơ tình nguyện viên, đề xuất sáng kiến, thông tin liên hệ, tài liệu tải lên và hình ảnh hoạt"}',datetime('now'),datetime('now'),datetime('now'));
INSERT OR IGNORE INTO pages(slug,title,status,blocks_json,seo_json,published_at,created_at,updated_at) VALUES ('accessibility','Khả năng tiếp cận','published','[{"type": "heading", "text": "Khả năng tiếp cận"}, {"type": "paragraph", "text": "Xanh Sky First hướng đến một website có thể được sử dụng bởi nhiều nhóm người dùng với thiết bị và khả năng tương tác khác nhau. Giao diện được định hướng hỗ trợ điều hướng bằng bàn phím, trạng thái focus rõ ràng, cấu trúc heading có thứ tự, nội dung ảnh có alt text phù hợp và độ tương phản đủ để đọc trong các ngữ cảnh thông thường. Các hiệu ứng chuyển động chỉ đóng vai trò bổ trợ; người dùng bật chế độ giảm chuyển động trên hệ điều hành sẽ nhận được trải nghiệm hạn chế animation. Biểu mẫu cần có label rõ ràng, thông báo lỗi đặt gần trường dữ liệu liên quan và không phụ thuộc duy nhất vào màu sắc để diễn đạt trạng thái. Xanh tiếp tục rà soát khả năng tiếp cận khi có nội dung, module hoặc công nghệ mới được thêm vào. Nếu bạn gặp một thành phần không thể thao tác bằng bàn phím, nội dung không đọc được bằng công nghệ hỗ trợ hoặc vấn đề tương phản, vui lòng gửi mô tả đến support@skyfirst.io.vn để đội ngũ có cơ sở kiểm tra và cải thiện."}, {"type": "heading", "text": "Liên hệ về nội dung này"}, {"type": "paragraph", "text": "Mọi phản hồi hoặc yêu cầu liên quan có thể gửi tới support@skyfirst.io.vn. Khi yêu cầu liên quan đến một hồ sơ cụ thể, Xanh có thể cần thông tin xác minh hợp lý trước khi cung cấp, chỉnh sửa hoặc xử lý dữ liệu nhằm bảo vệ quyền riêng tư của chính người gửi."}]','{"title": "Khả năng tiếp cận | Xanh Sky First", "description": "Xanh Sky First hướng đến một website có thể được sử dụng bởi nhiều nhóm người dùng với thiết bị và khả năng tương tác khác nhau. Giao diện được định hướng "}',datetime('now'),datetime('now'),datetime('now'));
INSERT OR IGNORE INTO pages(slug,title,status,blocks_json,seo_json,published_at,created_at,updated_at) VALUES ('sitemap','Sitemap','published','[{"type": "heading", "text": "Sitemap"}, {"type": "paragraph", "text": "Trang này cung cấp bản đồ điều hướng bằng HTML cho các khu vực công khai chính của Xanh Sky First. Danh sách liên kết được trình bày theo nhóm để người dùng có thể nhanh chóng đi đến phần giới thiệu, con người, dự án, hoạt động, cơ hội, tài nguyên, tin tức, biểu mẫu tham gia, thông tin liên hệ và những chính sách công khai. Song song với sitemap dành cho người đọc, hệ thống cung cấp /sitemap.xml cho công cụ tìm kiếm. Sitemap XML được tạo từ dữ liệu thực đang công khai, bao gồm các trang chính, nội dung đã xuất bản và hồ sơ Con người Xanh đã bật quyền lập chỉ mục. Những nội dung đang ở trạng thái nháp, hồ sơ nội bộ, đơn đăng ký và khu vực quản trị không được đưa vào sitemap công khai. Việc một URL xuất hiện trong sitemap không thay thế quyền kiểm soát index của từng nội dung; hồ sơ con người chỉ được thêm khi vừa công khai vừa bật cho phép công cụ tìm kiếm lập chỉ mục."}, {"type": "heading", "text": "Liên hệ về nội dung này"}, {"type": "paragraph", "text": "Mọi phản hồi hoặc yêu cầu liên quan có thể gửi tới support@skyfirst.io.vn. Khi yêu cầu liên quan đến một hồ sơ cụ thể, Xanh có thể cần thông tin xác minh hợp lý trước khi cung cấp, chỉnh sửa hoặc xử lý dữ liệu nhằm bảo vệ quyền riêng tư của chính người gửi."}]','{"title": "Sitemap | Xanh Sky First", "description": "Trang này cung cấp bản đồ điều hướng bằng HTML cho các khu vực công khai chính của Xanh Sky First. Danh sách liên kết được trình bày theo nhóm để người dùn"}',datetime('now'),datetime('now'),datetime('now'));

UPDATE pages SET blocks_json=replace(replace(blocks_json, '"#gioi-thieu"', '"/gioi-thieu"'), '"#tham-gia"', '"/tham-gia"'), updated_at=datetime('now') WHERE slug='home';
INSERT OR IGNORE INTO site_settings(key,value_json,updated_at) VALUES ('cms','{"autosave_seconds": 30, "revisions": true, "command_palette": true}',datetime('now'));
INSERT OR IGNORE INTO site_settings(key,value_json,updated_at) VALUES ('security','{"pbkdf2_iterations": 100000, "session_days": 7}',datetime('now'));
